kind: Secret
ansible_user: ENC[AES256_GCM,data:Mh6Y10w=,iv:mT78f9huMgeRTB1gtQv2sYz9p9gWQXd2y+zwlT15R0U=,tag:acnfLQ4hWFswEbufhj7AWg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BR/zHIHivW8ZwUquVA==,iv:QAE0MFjql7MBfnuqlNVCagm2LqkGBvJpuH4oPwLbX18=,tag:OpOZSleKqSt2bOeJT20rZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucnnx5euk9c7wp0lgmepaywjar7my70mu8k86pgvcznruhtk9gzsq5t8t0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWduWnF0cWEzd2E1THkx
            bDdEc3dkcFJuTzgydExZVjlLbEE4cDBTdG04CnFWdlh2U0dNbEQ4aVR1SnoyVk15
            ZHFWbG1NY2V5elgvU0hpdjJzWWxNRzQKLS0tIHBZR2w4Ni9xdWtkQ1paMndBZmpq
            MnVNOEF2TGtDRXhYVzRrajlPSmsreWMKH6qTBp8kDnIJG38E52kR6+btv3BFU7XO
            1mjRpqEmRj3jbYoXrMkwQlNgTbctvPHn9bayp5jZoFH0DdFrQP9L7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-07T02:04:49Z"
    mac: ENC[AES256_GCM,data:VHJCavKx7wA1SNBMyK0saq5iK8ud/DO01u/zwRsh4IMHEQq9S8YBjDYdf1cZMSeozDVnXeVbo1z3a/7ytEVKDQiHy5RzE6OqMfId0vzOt0KasTkEXkrUCKl3GShW8Cvyyrvzq6+b4BEp9W64z1wGzUKfjpBqwYv+QrPa7kyTj2M=,iv:e7putRM6JHEbOmeXW5nYAnPuIFu1ljmkcJULJYUUBfI=,tag:rQEtG05v58K9xt27eziWfA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
